### ISSUE TITLE
Error during run at step 3

### ISSUE THREAD

**Issue by istankov85** [tagbangers/wallride#62]
I run:
mvn spring-boot:run -P jar -Drun.jvmArguments=-Dwallride.home=file:www/
and here is the error:

[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) on project wallride: Unable to find a suitable main class, please add a 'mainClass' property -> [Help 1]

java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

**Comment by bourbonizable** [comment]
Hi @istankov85 !
Thank you for the comment,
It might because the first slash(/) in file path is missing for wallride.home argument,
which should be written as absolute path.
```
...  -Drun.jvmArguments=-Dwallride.home=file:/www/...
```
So, could you try running wallride with that argument again?

**Comment by hkkotha123** [comment]
mvn spring-boot:run -P jar -Drun.jvmArguments=-Dwallride.home=file:/WALLRIDE_HOME/

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) on project wallride: Unable to find a suitable main class, please add a 'mainClass' property -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

After adding / also i am getting above error please help

**Comment by bourbonizable** [comment]
Hi @hkkotha123, we are sorry for forgetting one more step to add in step3 that you should move to the "wallride-bootstrap" directory before executing mvn command.
```
cd wallride-bootstrap
mvn spring-boot:run -P jar -Drun.jvmArguments=-Dwallride.home=file:<WALLRIDE_HOME>/
```
We corrected (here)[https://github.com/tagbangers/wallride/wiki/Quick-start] as well.
would you try it again and let us know how it goes?

**Comment by hkkotha123** [comment]
hi ,
Thank you for the response, now moved a step and below is the new error i got

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.415 s
[INFO] Finished at: 2016-06-19T11:49:32-05:00
[INFO] Final Memory: 26M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project wallride-bootstrap: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

Thanks
Hari

**Comment by bourbonizable** [comment]
I'll close this issue now, if you have any problems about starting wallride, please open a new issue!
Thank you.

**Comment by Waleed-Zeddini** [comment]
HI,
I have this error message when clean or package or install:

Failed to execute goal on project wallride-bootstrap: Could not resolve dependencies for project org.wallride:wallride-bootstrap:war:1.0.0.BUILD-SNAPSHOT: Failed to collect dependencies at org.wallride:wallride-core:jar:1.0.0.BUILD-SNAPSHOT: Failed to read artifact descriptor for org.wallride:wallride-core:jar:1.0.0.BUILD-SNAPSHOT: Could not find artifact org.wallride:wallride:pom:1.0.0.BUILD-SNAPSHOT

**Comment by Waleed-Zeddini** [comment]
In the  ${packaging.type} always an error:
<artifactId>wallride-bootstrap</artifactId>
    <packaging>${packaging.type}</packaging>
    <name>WallRide Bootstrap</name>

**Comment by Waleed-Zeddini** [comment]
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.wallride:wallride-bootstrap >-------------------
[INFO] Building WallRide Bootstrap 1.0.0.BUILD-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:2.1.4.RELEASE:run (default-cli) > test-compile @ wallride-bootstrap >>>
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.820 s
[INFO] Finished at: 2021-11-25T19:12:32+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wallride-bootstrap: Could not resolve dependencies for project org.wallride:wallride-bootstrap:jar:1.0.0.BUILD-SNAPSHOT: Failed to collect dependencies at org.wallride:wallride-core:jar:1.0.0.BUILD-SNAPSHOT: Failed to read artifact descriptor for org.wallride:wallride-core:jar:1.0.0.BUILD-SNAPSHOT: Could not find artifact org.wallride:wallride:pom:1.0.0.BUILD-SNAPSHOT -> [Help 1]
[ERROR]

**Comment by bevrard** [comment]
> In the ${packaging.type} always an error: wallride-bootstrap ${packaging.type} WallRide Bootstrap

You should specify your type: jar or war

**Comment by Waleed-Zeddini** [comment]
thank you. done
