### ISSUE TITLE
Image linked to an article

### ISSUE THREAD

**Issue by bevrard** [tagbangers/wallride#67]
Hi,

How could we change the image of an article?

Thanks in advance.
Regards,

Benjamin

**Comment by bourbonizable** [comment]
Hi Benjamin, 
to change the image of an article, click the image you want to change
When the tooltip shows aside the image on the screen, click the reverse icon in that to show the "Drop image" area. Drag and drop another image to it to upload.
![screenshot00855](https://cloud.githubusercontent.com/assets/3993274/16233307/de409866-3808-11e6-9f88-04bccf620ed5.jpg)
![screenshot00856](https://cloud.githubusercontent.com/assets/3993274/16233340/f9ef6bb4-3808-11e6-880f-c37ca1d914d2.jpg)
![screenshot00858](https://cloud.githubusercontent.com/assets/3993274/16233588/e82a3f48-3809-11e6-8467-6c7ee81239db.jpg)
In case you want to delete the image, click the image again and click the trashcan icon.
We use beautiful [Froala](https://www.froala.com/wysiwyg-editor) wysiwyg editor for WallRide editor by the way.

**Comment by mainsys-crm** [comment]
Thanks for your answer.  Sorry but I was meaning "cover image".  Is it also a drag and drop area? or it's not yet available?

Benjamin

**Comment by bevrard** [comment]
Thanks for your answer. Sorry but I was meaning "cover image". Is it also a drag and drop area? or it's not yet available? Benjamin

**Comment by bourbonizable** [comment]
You're right, drag and drop to change cover image to the box named 'Cover image' as well. Apologies to make you confused.
When you want to remove it, click the remove icon(x) on upper right in the cover image box. 
![screenshot00861](https://cloud.githubusercontent.com/assets/3993274/16238543/cc4a7fa6-381b-11e6-96cf-235810846140.jpg)
![screenshot00862](https://cloud.githubusercontent.com/assets/3993274/16238539/c8c63168-381b-11e6-8f82-778f3037c7dc.jpg)

**Comment by bevrard** [comment]
Awesome! :-) If I have other questions like this one, should I create an issue or do you want to use another way of communication?
Last question: do you have a roadmap? because I'm planning to develop a event/calendar on your CMS, but if you've already done it or planned... I could wait :-D.  For futur features, should it use the pull requests section?

Thank you!

**Comment by bourbonizable** [comment]
Hi, apologies for the late reply. As of now, we use only github issues because we want to keep it simple about communicating tool. So if you have any questions, please post here as usual. In the future we might think about using ticket management systems like JIRA or chatting tools like gitter.
Yes we're planning about roadmap, but it's still private for now. If we can we will publish it in this month
but so far we don't plan to develop event/calendar. If it is okay, we would like to know what features the event calendar you want to make have. We might help some of the features.
Your pull requests are always welcome! To keep repository clean and simple, we make some guidelines to creating pull requests, but it'll be simple minimum ones. We will let you know it later.
When you create pr, please follow the guideline. 

Thank you.

**Comment by bevrard** [comment]
Hi,

For the event/calendar feature, I'm planning to create events in a new administrator panel.
These events could be show as a list or in a calendar view in the public website (based on fullcalendar.io)

Ok for pull requests, I will follow the guidelines.

For the development, I'm trying to use spring-boot-dev-tools.
I've put in the wall ride parent <dependencies>:
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
</dependency>

It starts the livereload but then I've an issue on my landing page.

Other question, is it possible to use Spring Loaded?

Regards,
Benjamin

**Comment by bourbonizable** [comment]
Hi, I'm so sorry for the late response!
Good to know about event calendar! but only administrators can see the calendar?

About long awaited PR guideline, We've created guideline [here](http://wallride.org/docs/guide.html#contribute), 
please take a look! Though this documentation is not enough(we know!)
it might be helpful for some part. 
This documentation can be seen in wallride.org site too. (Just click "Let's go ride now")

and regarding livereload, we know the issue and investigating that now.
The library urlrewritefilter of org.tuckey and livereload of spring-boot-devtools seems not going well... We're sorry for inconvenience for now.

Thank you.

**Comment by bourbonizable** [comment]
@bevrard Hi! Thank you for waiting..
We've updated the develop branch, which enables to use spring-boot-devtools.
We fixed the problem that wallride could not start normally by including devtools dependency to maven. 
Please checkout latest branch and start if you have time!

Thank you.
