### ISSUE TITLE
How are @WebGuestComponentScan and @WebAdminComponentScan meant to be used and when?

### ISSUE THREAD

**Issue by mhaddon** [tagbangers/wallride#68]
Why are they better than say @ComponentScan and what do they do differently.

**Comment by bourbonizable** [comment]
Hi @mhaddon !
WallRide separates a Context into 3 Contexts which are arranged in a hierarchy to isolate guest and admin site on a Bean basis; common (parent) Context, Guest site Context and Admin site Context (both are children) -- by using inheritance of ApplicationContext.
While @ComponentScan scans common Context, @WebGuestComponentScan scans Guest site Context and @WebAdminComponentScan does Admin one, respectively.

**Comment by bourbonizable** [comment]
I'll close this issue now, if you have any problems about starting wallride, please open a new issue!
Thank you.
